name: niobiumnotify

hooks:
  preprovision:
    shell: pwsh
    run: ./infra/scripts/SetAppSettings.ps1
  postprovision:
    - shell: pwsh
      run: ./infra/scripts/SetKeyVaultSecrets.ps1
    - shell: pwsh
      run: ./infra/scripts/ClearAppSettings.ps1

infra:
  provider: bicep
  layers:
    - name: niobiumnotify-infra
      path: ./infra

services:
  niobiumnotify:
    project: ./src/Niobium.Notification.Server
    language: csharp
    host: function
    hooks:
      prepackage:
        run: dotnet test --solution ../../Niobium.Notification.slnx --configuration Release

pipeline:
  provider: github