name: New Storage Account
description: Provision an Azure Storage Account using a Bicep module and return the raw deployment outputs JSON.

inputs:
 azure_credentials:
 description: JSON credentials for azure/login (ARM_* or federated)
 required: true
 resource_group:
 description: Resource group name
 required: true
 location:
 description: Azure location for deployment
 required: true
 storage_account_name:
 description: Storage Account name
 required: true
 contributor_principal_id:
 description: Optional AAD principal id to grant Contributor
 required: false
 default: ''
 allowed_origins:
 description: Allowed CORS origins
 required: false
 default: ''
 sku:
 description: Storage Account SKU (e.g., Standard_ZRS)
 required: false
 default: 'Standard_ZRS'
 bicep_file:
 description: Path to StorageAccount.bicep
 required: false
 default: 'bicep/modules/StorageAccount.bicep'
 enabled:
 description: Whether to run this step
 required: false
 default: 'true'

outputs:
 deployment_outputs_json:
 description: Raw JSON of properties.outputs from the deployment
 value: ${{ steps.outputs_json.outputs.deployment_outputs_json }}

runs:
 using: composite
 steps:
 - name: Checkout
 uses: actions/checkout@v4

 - name: Azure Login
 if: ${{ inputs.enabled == 'true' }}
 uses: azure/login@v2
 with:
 creds: ${{ inputs.azure_credentials }}

 - id: deploy
 if: ${{ inputs.enabled == 'true' }}
 name: Deploy Storage Account via Bicep
 shell: bash
 env:
 RG: ${{ inputs.resource_group }}
 LOC: ${{ inputs.location }}
 BICEP: ${{ inputs.bicep_file }}
 NAME: ${{ inputs.storage_account_name }}
 OWNER: ${{ inputs.contributor_principal_id }}
 ORIGINS: ${{ inputs.allowed_origins }}
 SKU: ${{ inputs.sku }}
 run: |
 set -euo pipefail
 az group create -n "$RG" -l "$LOC"
 PARAMS=(
 "storageAccountName=$NAME"
 "allowedOrigins=$ORIGINS"
 "storageAccountSku=$SKU"
 )
 if [[ -n "$OWNER" ]]; then
 PARAMS+=("contributorPrincipalId=$OWNER")
 fi
 az deployment group create \
 -g "$RG" \
 -n DeployPipelineTemplate \
 -f "$BICEP" \
 -p "${PARAMS[@]}"

 - id: outputs_json
 if: ${{ inputs.enabled == 'true' }}
 name: Fetch deployment outputs
 shell: bash
 env:
 RG: ${{ inputs.resource_group }}
 run: |
 set -euo pipefail
 JSON=$(az deployment group show -g "$RG" -n DeployPipelineTemplate --query properties.outputs -o json || echo '{}')
 {
 echo "deployment_outputs_json<<EOF"
 echo "$JSON"
 echo EOF
 } >> "$GITHUB_OUTPUT"
