name: Publish

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/publish-job.yml
    with:
      environment: 'test'
      version_suffix: '-prerelease'
      run_integration_test: true
      deploy_assets: false
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
      CUSTOM_DOMAIN_CERTIFICATE_NAME: ${{ secrets.CUSTOM_DOMAIN_CERTIFICATE_NAME }}
      APPSETTING_NOTIFICATIONOPTIONS__SELFHOSTNAME: ${{ secrets.APPSETTING_NOTIFICATIONOPTIONS__SELFHOSTNAME }}
      APPSETTING_RESENDSERVICEOPTIONS__GLOBALAPIKEY: ${{ secrets.APPSETTING_RESENDSERVICEOPTIONS__GLOBALAPIKEY }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBAR_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBAR_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMISSIONBAY_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMISSIONBAY_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMORNINGSIDE_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMORNINGSIDE_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESHAMILTON_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESHAMILTON_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_NIOBIUM_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_NIOBIUM_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_TAPSS_CARE: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_TAPSS_CARE }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_ZAPS_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_ZAPS_CO_NZ }}
      APPSETTING_RESENDSERVICEOPTIONS__DOMAINSCOPEDAPIKEYS__TAPSS_CARE: ${{ secrets.APPSETTING_RESENDSERVICEOPTIONS__DOMAINSCOPEDAPIKEYS__TAPSS_CARE }}
  prod:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    uses: ./.github/workflows/publish-job.yml
    with:
      environment: 'prod'
      version_suffix: ''
      run_integration_test: false
      deploy_assets: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CUSTOM_DOMAIN_NAME: ${{ secrets.CUSTOM_DOMAIN_NAME }}
      CUSTOM_DOMAIN_CERTIFICATE_NAME: ${{ secrets.CUSTOM_DOMAIN_CERTIFICATE_NAME }}
      APPSETTING_NOTIFICATIONOPTIONS__SELFHOSTNAME: ${{ secrets.APPSETTING_NOTIFICATIONOPTIONS__SELFHOSTNAME }}
      APPSETTING_RESENDSERVICEOPTIONS__GLOBALAPIKEY: ${{ secrets.APPSETTING_RESENDSERVICEOPTIONS__GLOBALAPIKEY }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBAR_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBAR_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMISSIONBAY_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMISSIONBAY_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMORNINGSIDE_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESBARMORNINGSIDE_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESHAMILTON_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_EDENNOODLESHAMILTON_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_NIOBIUM_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_NIOBIUM_CO_NZ }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_TAPSS_CARE: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_TAPSS_CARE }}
      APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_ZAPS_CO_NZ: ${{ secrets.APPSETTING_CAPTCHAOPTIONS__SECRETS__WWW_ZAPS_CO_NZ }}
      APPSETTING_RESENDSERVICEOPTIONS__DOMAINSCOPEDAPIKEYS__TAPSS_CARE: ${{ secrets.APPSETTING_RESENDSERVICEOPTIONS__DOMAINSCOPEDAPIKEYS__TAPSS_CARE }}
